// Mocks generated by Mockito 5.4.2 from annotations
// in jobspot/test/features/add_post/add_post_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jobspot/src/core/resources/data_state.dart' as _i2;
import 'package:jobspot/src/presentations/add_post/domain/entities/add_post_entity.dart'
    as _i5;
import 'package:jobspot/src/presentations/add_post/domain/entities/update_post_entity.dart'
    as _i7;
import 'package:jobspot/src/presentations/add_post/domain/use_cases/add_post_use_case.dart'
    as _i3;
import 'package:jobspot/src/presentations/add_post/domain/use_cases/update_post_use_case.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddPostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddPostUseCase extends _i1.Mock implements _i3.AddPostUseCase {
  MockAddPostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<dynamic>> call(
          {required _i5.AddPostEntity? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.DataState<dynamic>>.value(_FakeDataState_0<dynamic>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.DataState<dynamic>>);
}

/// A class which mocks [UpdatePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePostUseCase extends _i1.Mock implements _i6.UpdatePostUseCase {
  MockUpdatePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<dynamic>> call(
          {required _i7.UpdatePostEntity? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.DataState<dynamic>>.value(_FakeDataState_0<dynamic>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.DataState<dynamic>>);
}
