// Mocks generated by Mockito 5.4.2 from annotations
// in jobspot/test/features/home_admin/home_admin_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jobspot/src/core/resources/data_state.dart' as _i2;
import 'package:jobspot/src/core/resources/fetch_lazy_data.dart' as _i5;
import 'package:jobspot/src/presentations/home_admin/domain/entities/consider_company.dart'
    as _i8;
import 'package:jobspot/src/presentations/home_admin/domain/entities/verify_company_entity.dart'
    as _i6;
import 'package:jobspot/src/presentations/home_admin/domain/use_cases/consider_company_use_case.dart'
    as _i7;
import 'package:jobspot/src/presentations/home_admin/domain/use_cases/get_list_company_pending_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetListCompanyPendingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListCompanyPendingUseCase extends _i1.Mock
    implements _i3.GetListCompanyPendingUseCase {
  MockGetListCompanyPendingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i5.FetchLazyData<_i6.VerifyCompanyEntity>>> call(
          {required int? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<
                _i2
                .DataState<_i5.FetchLazyData<_i6.VerifyCompanyEntity>>>.value(
            _FakeDataState_0<_i5.FetchLazyData<_i6.VerifyCompanyEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4
          .Future<_i2.DataState<_i5.FetchLazyData<_i6.VerifyCompanyEntity>>>);
}

/// A class which mocks [ConsiderCompanyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockConsiderCompanyUseCase extends _i1.Mock
    implements _i7.ConsiderCompanyUseCase {
  MockConsiderCompanyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<bool>> call(
          {required _i8.ConsiderCompany? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.DataState<bool>>.value(_FakeDataState_0<bool>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.DataState<bool>>);
}
