class AppImages {
  AppImages._();

  static String onBoarding = "assets/images/intro_image.svg";
  static String google = "assets/images/google.svg";
  static String logo = "assets/images/logo.svg";
  static String forgotPassword = "assets/images/forgot_password.svg";
  static String checkEmail = "assets/images/check_email.svg";
  static String verifySuccess = "assets/images/verify_success.svg";
  static String clock = "assets/images/clock.svg";
  static String comment = "assets/images/comment.svg";
  static String share = "assets/images/share.svg";
  static String save = "assets/images/save.svg";
  static String saved = "assets/images/saved.svg";
  static String saveJob = "assets/images/save_job.svg";
  static String noSave = "assets/images/no_save.svg";
  static String findJob = "assets/images/find_job.svg";
  static String home = "assets/images/home.svg";
  static String connection = "assets/images/connection.svg";
  static String notification = "assets/images/notification.svg";
  static String send = "assets/images/send.svg";
  static String trash = "assets/images/trash.svg";
  static String checkCircle = "assets/images/check_circle.svg";
  static String camera = "assets/images/camera.svg";
  static String picture = "assets/images/picture.svg";
  static String edit = "assets/images/edit.svg";
  static String upload = "assets/images/upload.svg";
  static String pdf = "assets/images/pdf.svg";
  static String applySuccess = "assets/images/apply_success.svg";
  static String setting = "assets/images/setting.svg";
  static String profileBackground = "assets/images/profile_background.svg";
  static String language = "assets/images/language.svg";
  static String circleProfile = "assets/images/circle_profile.svg";
  static String bag = "assets/images/bag.svg";
  static String graduationCap = "assets/images/graduation_cap.svg";
  static String skill = "assets/images/skill.svg";
  static String archive = "assets/images/archive.svg";
  static String resume = "assets/images/resume.svg";
  static String logOut = "assets/images/log_out.svg";
  static String lock = "assets/images/lock.svg";
  static String vietnam = "assets/images/vietnam.svg";
  static String english = "assets/images/united_kingdom.svg";
  static String gallery = "assets/images/gallery.svg";
  static String openBrowser = "assets/images/open_browser.svg";
  static String filter = "assets/images/filter.svg";
}
