// Mocks generated by Mockito 5.4.2 from annotations
// in jobspot/test/features/test_iq/test_iq_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jobspot/src/core/resources/data_state.dart' as _i2;
import 'package:jobspot/src/presentations/test_iq/domain/entities/add_result_test_iq_entity.dart'
    as _i7;
import 'package:jobspot/src/presentations/test_iq/domain/entities/question_entity.dart'
    as _i5;
import 'package:jobspot/src/presentations/test_iq/domain/use_cases/add_result_test_iq_use_case.dart'
    as _i6;
import 'package:jobspot/src/presentations/test_iq/domain/use_cases/get_list_question_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetListQuestionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListQuestionUseCase extends _i1.Mock
    implements _i3.GetListQuestionUseCase {
  MockGetListQuestionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<List<_i5.QuestionEntity>>> call({dynamic params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i5.QuestionEntity>>>.value(
            _FakeDataState_0<List<_i5.QuestionEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i5.QuestionEntity>>>);
}

/// A class which mocks [AddResultTestIQUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddResultTestIQUseCase extends _i1.Mock
    implements _i6.AddResultTestIQUseCase {
  MockAddResultTestIQUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<bool>> call(
          {required _i7.AddResultTestIQEntity? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.DataState<bool>>.value(_FakeDataState_0<bool>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.DataState<bool>>);
}
