// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5e0u4uk-c5DVdtIZmbsFp-jzMK45wq30',
    appId: '1:126210642252:web:80e81172fd11d0463a3fe9',
    messagingSenderId: '126210642252',
    projectId: 'walter-jobspot',
    authDomain: 'walter-jobspot.firebaseapp.com',
    storageBucket: 'walter-jobspot.appspot.com',
    measurementId: 'G-WXHMDY9C6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2e75hYl_fghF6fO1qFXwu31FiONIz60',
    appId: '1:126210642252:android:df72db6b111e578e3a3fe9',
    messagingSenderId: '126210642252',
    projectId: 'walter-jobspot',
    storageBucket: 'walter-jobspot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ3l2Ick1Erdmf3UvXZlnPn-CLh4Zir5g',
    appId: '1:126210642252:ios:06f54a2c1c48430b3a3fe9',
    messagingSenderId: '126210642252',
    projectId: 'walter-jobspot',
    storageBucket: 'walter-jobspot.appspot.com',
    iosBundleId: 'com.walter.jobspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ3l2Ick1Erdmf3UvXZlnPn-CLh4Zir5g',
    appId: '1:126210642252:ios:254663782514a53c3a3fe9',
    messagingSenderId: '126210642252',
    projectId: 'walter-jobspot',
    storageBucket: 'walter-jobspot.appspot.com',
    iosBundleId: 'com.walter.jobspot.RunnerTests',
  );
}
